cafe/urls.py
from filebrowser.sites import site
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$',                          'cafe.views.index'),
    url(r'^admin/',                     include(admin.site.urls)),
    url(r'^news/',                      include('news.urls')),
    url(r'^post/',                      include('news.urls')),
    url(r'^tag/(?P<tagname>[-\w]+)/$',  'news.views.tagged_items'),
    url(r'^newpost/',                   'cafe.views.index'),
    url(r'^admin/filebrowser/',         include(site.urls)),
    url(r'^user/',                      include('cafe.userurls')),
    url(r'^comments/$',                 'news.views.comment_listing'),
    url(r'^game/',                      include('news.caturls')),
    url(r'^openid/complete/$',          'cafe.views.login'),
    url(r'^openid/',                    include('django_openid_auth.urls')),
    url(r'^logout/$',                   'cafe.views.logout_view'),
    #url(r'^pysg/',                      include('pysg_django.urls')),
    url(r'comments/posted/$',           'news.views.comment_posted'),
    url(r'^comments/',                  include('django.contrib.comments.urls')),
    #url(r'^stats/',                     include('cafe.statsurls')),
    url(r'^grappelli/',                 include('grappelli.urls')),
    url(r'^ckeditor/',                  include('ckeditor.urls')),
    url(r'^server/',                    include('srcquery.urls')),
    url(r'^map/(?P<mapname>.+)/$',      'srcquery.views.map_detail'),
)

if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
        }),
    )

cafe/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.comments.models import Comment
from news.models import NewsPost

class UserProfile(models.Model):
    LEVEL_NAMES = (
        (u'0',  u'Staff'),
        (u'1',  u'Cool Kid'),
        (u'2',  u'Regular'),
        (u'3',  u'Patron'),
    )

    user = models.OneToOneField(User)

    # This will update their steam information every time they log in or something I guess yeah that sounds good.
    handle = models.CharField(max_length=50, blank=True)
    steamid = models.CharField(max_length=50, blank=True)
    url = models.CharField(max_length=255, blank=True)
    avatar = models.CharField(max_length=255, blank=True)
    avatarM = models.CharField(max_length=255, blank=True)
    avatarL = models.CharField(max_length=255, blank=True)
    primarygroup = models.CharField(max_length=50, blank=True)
    realname = models.CharField(max_length=50, blank=True)

    # This is the cafe stuff
    level = models.CharField(max_length=2, choices=LEVEL_NAMES, blank=True)

    def get_postcount(self):
        return NewsPost.objects.filter(author=self.user).count()

    def get_commentcount(self):
        return Comment.objects.filter(user=self.user).count()

    def __unicode__(self):
        return self.handle

def create_user_profile(sender, instance, created, **kw):
    if created:
        UserProfile.objects.create(user=instance)

news/models.py
from datetime import timedelta
from django.db import models
from django.contrib.comments.models import Comment
from django.utils import timezone
from django.template.defaultfilters import slugify
from tagging.fields import TagField
import re

def unique_slugify(instance, value, slug_field_name='slug', queryset=None,
                   slug_separator='-'):
    """
    Calculates and stores a unique slug of ``value`` for an instance.

    ``slug_field_name`` should be a string matching the name of the field to
    store the slug in (and the field to check against for uniqueness).

    ``queryset`` usually doesn't need to be explicitly provided - it'll default
    to using the ``.all()`` queryset from the model's default manager.
    """
    slug_field = instance._meta.get_field(slug_field_name)

    slug = getattr(instance, slug_field.attname)
    slug_len = slug_field.max_length

    # Sort out the initial slug, limiting its length if necessary.
    slug = slugify(value)
    if slug_len:
        slug = slug[:slug_len]
    slug = _slug_strip(slug, slug_separator)
    original_slug = slug

    # Create the queryset if one wasn't explicitly provided and exclude the
    # current instance from the queryset.
    if queryset is None:
        queryset = instance.__class__._default_manager.all()
    if instance.pk:
        queryset = queryset.exclude(pk=instance.pk)

    # Find a unique slug. If one matches, at '-2' to the end and try again
    # (then '-3', etc).
    next = 2
    while not slug or queryset.filter(**{slug_field_name: slug}):
        slug = original_slug
        end = '%s%s' % (slug_separator, next)
        if slug_len and len(slug) + len(end) > slug_len:
            slug = slug[:slug_len-len(end)]
            slug = _slug_strip(slug, slug_separator)
        slug = '%s%s' % (slug, end)
        next += 1

    setattr(instance, slug_field.attname, slug)


def _slug_strip(value, separator='-'):
    """
    Cleans up a slug by removing slug separator characters that occur at the
    beginning or end of a slug.

    If an alternate separator is used, it will also replace any instances of
    the default '-' separator with the new separator.
    """
    separator = separator or ''
    if separator == '-' or not separator:
        re_sep = '-'
    else:
        re_sep = '(?:-|%s)' % re.escape(separator)
    # Remove multiple instances and if an alternate separator is provided,
    # replace the default '-' separator.
    if separator != re_sep:
        value = re.sub('%s+' % re_sep, separator, value)
    # Remove separator from the beginning and end of the slug.
    if separator:
        if separator != '-':
            re_sep = re.escape(separator)
        value = re.sub(r'^%s+|%s+$' % (re_sep, re_sep), '', value)
    return value

class Category(models.Model):
    name = models.CharField(max_length=50)
    icon = models.ImageField(upload_to='img/icon')
    abv = models.CharField(max_length=5)
    tags = TagField()

    def get_absolute_url(self):
        return "/game/{0}".format(self.abv)

    class Meta:
        verbose_name_plural = "games"
        verbose_name = "game"

    def __unicode__(self):
        return self.name


class Blurb(models.Model):
    who = models.CharField(max_length=128)
    user = models.ForeignKey('auth.User', blank=True, null=True)
    said = models.CharField(max_length=435)
    pub_date = models.DateTimeField('when', blank=True, auto_now_add=True)


    def get_absolute_url(self):
        return "/blurb/{0}".format(self.id)

    def __unicode__(self):
        return "{0}: {1}".format(self.who, self.said[:140])

class NewsPost(models.Model):
    title = models.CharField(max_length=200)
    slug = models.CharField(max_length=200, blank=True)
    body = models.TextField()
    tags = TagField()
    category = models.ForeignKey('Category', blank=True, null=True)
    pub_date = models.DateTimeField('date published', auto_now_add=True)
    author = models.ForeignKey('auth.User')
    bulletin = models.BooleanField(blank=False, default=False)
    secret = models.CharField(max_length=32, blank=True)

    def save(self):
        if not self.id:
            unique_slugify(self, self.title)

        super(NewsPost, self).save()

    def get_absolute_url(self):
        return "/post/{0}".format(self.slug)

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - timedelta(hours=1)

    def get_latest_comment(self):
        try:
            comment = Comment.objects.filter(object_pk=self.id).exclude(is_removed=True).order_by('-id')[0]
        except IndexError:
            comment = None
        return comment

    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

    def __unicode__(self):
        return self.title

cafe/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.conf import settings
from django.contrib.auth import logout, authenticate, login as auth_login
from django.contrib.auth.models import User
from django.contrib.comments import Comment
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Count
from django.template import RequestContext
from django.shortcuts import render_to_response, get_object_or_404
from django_openid_auth.models import UserOpenID
from django_openid_auth.views import parse_openid_response
from news.models import NewsPost, Category, Blurb
from news.forms import NewPostForm
from cafe.models import UserProfile
from tagging.models import Tag
import json
import urllib
import datetime
from itertools import chain

def index(request):
    try:
        post_list = NewsPost.objects.all()
    except IndexError:
        post_list = None

    try:
        blurb_list = Blurb.objects.all()
    except IndexError:
        blurb_list = None

    result_list = sorted(
        chain(post_list, blurb_list),
        key = lambda instance: instance.pub_date, reverse=True)

    categories = NewsPost.objects.values('category').annotate(Count('category')).order_by('-category__count')
    catlist = []
    for cat in categories:
        if cat['category']:
            newcat = Category.objects.get(pk=cat['category'])
            catlist.append(newcat)

    tags = Tag.objects.usage_for_model(NewsPost, min_count=2)

    if request.method == 'POST':
        f = NewPostForm(request.POST)
        if f.is_valid():
            newpost = f.save(commit=False)
            newpost.author = request.user
            newpost.pub_date = datetime.datetime.now()
            newpost.save()
            return HttpResponseRedirect(newpost.get_absolute_url())
        else:
            form = f

    else:
        form = NewPostForm()

    paginator = Paginator(result_list, 20)
    page = request.GET.get('page')

    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    return render_to_response('cafe/home.html', {'form': form, 'posts': posts, 'categories': catlist, 'taglist': tags}, context_instance=RequestContext(request))

def login(request):
    data = {}
    data['response'] = request.GET["openid.claimed_id"]
    data['id'] = request.GET["openid.claimed_id"][36:]
    data['url'] = "http://api.steampowered.com/ISteamUser/GetPlayerSummaries/v0002/?key="+settings.STEAM_API_KEY+"&steamids="+data['id']

    claim = data['response']

    # Get public info
    data['info'] = json.loads(urllib.urlopen(data["url"]).read())["response"]["players"][0]

    handle = data['info']['personaname']
    steamid = data['info']['steamid']
    url = data['info']['profileurl']
    avatar = data['info']['avatar']
    avatarM = data['info']['avatarmedium']
    avatarL = data['info']['avatarfull']
    try:
        primarygroup = data['info']['primaryclanid']
    except KeyError:
        primarygroup = ""
    try:
        realname = data['info']['realname']
    except KeyError:
        realname = ""

    # Find the user
    try:
        useroid = UserOpenID.objects.get(claimed_id=claim)
        user = User.objects.get(username=steamid)
    # New user
    except UserOpenID.DoesNotExist:
        user = User.objects.create_user(username=steamid, email='', password='!')
        user.save()
        useroid = UserOpenID(user=user, claimed_id=claim, display_id=claim)
        useroid.save()
    try:
        up = UserProfile.objects.get(user_id=user.id)
        print "Found user profile"
    except UserProfile.DoesNotExist:
        print "No user profile"
        up = UserProfile(user_id=user.id)
        up.save()

    # User exists, fill out profile, which is auto-filled with blanks atm.
    up.handle=handle
    up.steamid=steamid
    up.url=url
    up.avatar=avatar
    up.avatarM=avatarM
    up.avatarL=avatarL
    up.primarygroup=primarygroup
    up.realname=realname

    up.save()


    # Stole these lines from inside the openid_auth files. idk why now
    # PROB. IMPORTANT THO
    openid_response = parse_openid_response(request)
    user = authenticate(openid_response=openid_response)

    auth_login(request, user)

    return HttpResponseRedirect('/')

def logged(request):
    return HttpResponse('Logged in!')

def logout_view(request):
    logout(request)
    return HttpResponse('Logged out home-slice.')

# User Views
def user_index(request, id):
    cafeuser = get_object_or_404(User, pk=id)

    comments = Comment.objects.all().filter(user=cafeuser).exclude(is_removed=True).order_by('-id')[:5]
    posts = NewsPost.objects.all().filter(author=cafeuser).order_by('-pub_date')[:5]

    categories = NewsPost.objects.values('category').annotate(Count('category')).order_by('-category__count')
    catlist = []
    for cat in categories:
        if cat['category']:
            newcat = Category.objects.get(pk=cat['category'])
            catlist.append(newcat)

    tags = Tag.objects.usage_for_model(NewsPost, min_count=3)[:5]

    return render_to_response('cafe/user_index.html',
                              {'categories':catlist, 'cafeuser':cafeuser, 'comments':comments, 'posts':posts, 'taglist':tags},
                context_instance=RequestContext(request))

def user_posts(request, id, cat=None):
    cafeuser = get_object_or_404(User, pk=id)
    post_list = NewsPost.objects.all().filter(author=cafeuser).order_by('-pub_date')
    if cat:
        post_list = post_list.filter(category__abv=cat)
    categories = NewsPost.objects.values('category').annotate(Count('category')).order_by('-category__count')
    catlist = []
    for cat in categories:
        if cat['category']:
            newcat = Category.objects.get(pk=cat['category'])
            catlist.append(newcat)

    tags = Tag.objects.usage_for_model(NewsPost, min_count=3)[:5]
    paginator = Paginator(post_list, 10)
    curpage = request.GET.get('page')

    try:
        posts = paginator.page(curpage)
    except (PageNotAnInteger, AttributeError):
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    return render_to_response('cafe/user_post_listing.html',
                              {'posts': posts, 'categories':catlist, 'cafeuser':cafeuser, 'taglist':tags},
                                context_instance=RequestContext(request))

def user_comments(request, id, cat=None):
    cafeuser = get_object_or_404(User, pk=id)
    comment_list = Comment.objects.filter(user=cafeuser).exclude(is_removed=True).order_by('-id')
    categories = NewsPost.objects.values('category').annotate(Count('category')).order_by('-category__count')
    catlist = []
    for cat in categories:
        if cat['category']:
            newcat = Category.objects.get(pk=cat['category'])
            catlist.append(newcat)

    tags = Tag.objects.usage_for_model(NewsPost, min_count=3)[:5]
    paginator = Paginator(comment_list, 10)
    page = request.GET.get('page')

    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    return render_to_response('cafe/user_comment_listing.html',
                              {'posts': posts, 'categories':catlist, 'cafeuser':cafeuser, 'taglist':tags},
                                context_instance=RequestContext(request))

templates/cafe/home.html
{% extends "layout.html" %}

{% load staticfiles %}
{% load post_filters %}
{% load humanize %}
{% load tagging_tags %}

{% block head %}<script type="text/javascript" src="{% static "js/msdropdown/jquery.dd.min.js" %}"></script>
        {{ form.media }}{% endblock head %}

{% load comments %}

{% block navbar %}{% if perms.news.add_newspost and not cat and not tag %}<div class="nav"><a href="#" id="postlink" class="navblip" title="Make a Post! Show them all!">+ post</a></div>{% endif %}{% endblock navbar %}

{% block content %}
<div id="news">
    <div id="newpost" class="post" {% if form.errors %} style="display: block;"{% else %}style="display:none;"{% endif %}>
            {% for error in form.errors %}<strong>{{ form.error }}</strong>{% endfor %}
            <form action="newpost/" method="post">{% csrf_token %}
                {{ form.title }}
                {% if form.title.errors %}<span class="error">You forgot a title!</span>{% endif %}
                <br>
                <br>
                {{ form.body }}<br>
                {% if form.body.errors %}<span class="error">You forgot... the body? How?</span>{% endif %}
                <div class="posthints">
                    <ul>
                        <li>If you have a long post, put &lt;!--more--&gt; in the Source.</li>
                        <li>Max width is 1024px, but you only have ~900px to play with.</li>
                        <li>Don't steal shit. Reblog and source. SOURCE YOUR SHIT.</li>
                    </ul>
                </div>
                <label for="id_category">Game:</label> {{ form.category }}<br>
                {{ form.category.errors }}
                <label for="id_tags">Tags (<a href="http://beta.cafeofbrokendreams.com:8000/post/tagging-faq/" target="_blank">FAQ</a>)</label> {{ form.tags }}<br>
                <label for="id_bulletin">Make this a Temporary Bulletin:</label> {{ form.bulletin }}
                <br>
                <input type="submit" value="Submit" />
            </form>
        </div>
    <h1 style="display: block; text-align: center;">{% if cat %}{{ cat }}{% elif tag %}#{{ tag }}{% endif %}</h1>
    {% if posts %}
        {% for post in posts %}
        <div {% if post.bulletin %}class="bullet{% if not post.was_published_recently %}_old{% endif %}"{% elif post.said %}class="blurb"{% else %}class="post"{% endif%} {% if post.category and not post.bulletin %}style="background-image:url('/media/{{ post.category.icon }}');"{% endif %}>
            <div class="phead">
                <a class="title" href="{{ post.get_absolute_url }}" title="{{ post.title }}">{% if post.category and post.category.abv != 'cafe' %}<span class="cat">{{ post.category.abv }}</span> // {% endif %}{{ post.title }}</a>
            </div>
            <div class="pbody">
                {% if not post.category or post.category.abv == 'cafe' %}
                <span class="pubdate">posted {{ post.pub_date|naturaltime }}</span>{% if post.category %}<span class="game">- <a href="{{ post.category.get_absolute_url }}">{{ post.category }}</a></span>{% endif %}
                {% if post.user %}{{ post.pub_date|naturalday }} <img src="{{ post.user.get_profile.avatar }}"> &quot;{{ post.said }}&quot;{% elif post.who %}<em>{{ post.pub_date|naturalday }}</em> <u>{{ post.who }}</u> &quot;{{ post.said }}&quot;{% else %}{{ post.body|safe|read_more:post.get_absolute_url }}{% endif %}
                {% endif %}
            </div>
            {% if not post.category or post.category.abv == 'cafe' %}
            <div class="postfoot">
                <span class="auth"><a href="/user/{{ post.author.id }}" title="{{ post.author.get_profile.handle }}'s User Page"><img src="{{ post.author.get_profile.avatar }}" /></a></span>
                <span class="tags">{% tags_for_object post as tags %}{% for tag in tags %}<a href="/tag/{{ tag.slug }}">#{{ tag }}</a> {% endfor %}</span>
            </div>
            {% endif %}
            {% if not post.category or post.category.abv == 'cafe' %}
                {% with post.get_latest_comment as comment %}
                    {% if comment %}
                        <div class="lastword">
                            <a class="comav" href="{{ comment.get_absolute_url }}"><img src="{{ comment.user.get_profile.avatar }}" alt="{{ comment.user.get_profile.handle }}" /></a>
                            <span class="comquip">{{ comment.comment|safe|truncatewords:25 }}</span>
                        </div>
                    {% endif %}
                {% endwith %}
            {% else %}
                {% get_comment_count for post as comcount %}
                    {% if comcount %}
                    <span class="minicomlink"><a href="{{ post.get_latest_comment.get_absolute_url }}">{{ comcount }} comment{{ comcount|pluralize }}</a></span>
                    {% endif %}
            {% endif %}
        </div><!-- post -->
        {% endfor %}
        <div id="pagination">
            {% if posts.has_previous %}
                <a href="?page={{ posts.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ posts.number }} of {{ posts.paginator.num_pages }}
            </span>

            {% if posts.has_next %}
                <a href="?page={{ posts.next_page_number }}">next</a>
            {% endif %}
        </div>
    {% else %}
        <p>There is either no news or doc is fixing something. "Fixing".</p>
    {% endif %}
</div>
<div id="sidebar">
    <div class="serverlist">
        <h1 class="title">Servers</h1>
        <ul>
            <li>will go here</li>
        </ul>
    </div>

    <div class="comments">
        <h1 class="title">Latest Comments</h1>
        <ul>
            <li><span class="who">CBAG</span> <span class="what">[THIS KEYBOARD] MUST BE WHAT IT SOUNDS LIKE WHEN ROBOTS GIVE HANDJOBS</span></li>
        </ul>
    </div>

    <div class="maps">
        <h1 class="title">Newest Maps</h1>
        <ul>
            <li><span class="mapname">be_nat20_a0</span> by <span class="mapwho">A Whole Clan of Johnnies</span></li>
        </ul>
    </div>
</div>
{% endblock content %}

templates/cafe/logged.html
{% if user.is_authenticated %}
    Logged in!<br>
    user: {{ user }}<br>
    username: {{ user.username }}<br>
    email: {{ user.email }}<br>
    <a href="/logout">logout</a>
{% else %}
    <a href="/openid/login">Please log in.</a>
{% endif %}

templates/cafe/newpost.html
{% extends "layout.html" %}

{% load post_filters %}
{% load tagging_tags %}

{% block head %}{{ form.media }}{% endblock head %}

{% load comments %}

{% block navbar %}{% if perms.news.add_newspost and not cat and not tag %}<div class="nav"><a href="#" id="postlink" class="navblip" title="Make a Post! Show them all!">+ post</a></div>{% endif %}{% endblock navbar %}

{% block content %}
<div id="news">
        <div id="newpost" class="post" style="display:none;">
            <form action="newpost/" method="post">{% csrf_token %}
                <label for="id_title">Title:</label> {{ form.title }}
                <br>
                <br>
                {{ form.body }}<br>
                <div class="posthints">
                    <ul>
                        <li>If you have a long post, put &lt;!--more--&gt; in the Source.</li>
                        <li>Max width is 750x, but you only have ~740px to play with.</li>
                        <li>Don't steal shit. Reblog and source. SOURCE YOUR SHIT.</li>
                    </ul>
                </div>
                <label for="id_category">Game:</label> {{ form.category }}<br>
                <label for="id_tags">Tags (<a href="http://beta.cafeofbrokendreams.com:8000/post/tagging-faq/" target="_blank">FAQ</a>)</label> {{ form.tags }}<br>
                <label for="id_bulletin">Make this a Temporary Bulletin:</label> {{ form.bulletin }}
                <br>
                <input type="submit" value="Submit" /> 
            </form>
        </div>
    <h1 style="display: block; text-align: center;">{% if cat %}{{ cat }}{% elif tag %}#{{ tag }}{% endif %}</h1>
    {% if bulletin and bulletin.was_published_recently %}
    {% with bulletin as post %}
    <div id="bullet">
    <div class="post">
        <h1><a href="{{ post.get_absolute_url }}" title="{{ post.title }}">{{ post.title }}</a></h1><br>
        <p>{{ post.body|read_more:post.get_absolute_url|safe }}</p>
        <br />
        <div class="byline">
            <a href="/game/{{ post.category.abv }}" title="{{ post.category }} posts">{{ post.category.name }}</a>
        </div>
    </div><!-- post -->
</div><!-- bullet -->
    {% endwith %}
    {% endif %}

    {% if posts %}
        {% for post in posts %}
        {% if not post.bulletin %}
            <div class="post">
                <h1><a href="{{ post.get_absolute_url }}" title="{{ post.title }}">{{ post.title }}</a></h1>
                <h5 class="pubdate">{{ post.pub_date|naturaltime }}</h5>
                <p>{{ post.body|safe|read_more:post.get_absolute_url }}</p>
                <br />
                <div class="byline">
                    {% if post.category %}<a href="/game/{{ post.category.abv }}" title="{{ post.category }} posts"><img src="/media/{{ post.category.icon }}" /></a> {% endif %}<a href="/user/{{ post.author.id }}" title="{{ post.author.get_profile.handle }}'s User Page"><img src="{{ post.author.get_profile.avatarM }}" /></a>
                </div>
                <span class="tags">{% tags_for_object post as tags %}{% for tag in tags %}<a href="/tag/{{ tag.slug }}">#{{ tag }}</a> {% endfor %}</span>
            </div><!-- post -->

            {% with post.get_latest_comment as comment %}
                {% if comment %}
                    <div class="onecomment">
                        <a href="/user/{{ comment.user.id }}" title="{{ comment.user.get_profile.handle }}'s User Page"><img src="{{ comment.user.get_profile.avatar }}" alt="{{ comment.user.get_profile.handle }}" /></a> {{ comment.user.get_profile.handle }}<br>
                        <p>{{ comment.comment|safe|truncatechars:140 }}</p>
                        <a href="{{ post.get_absolute_url }}" title="Comment" />comment</a>
                    </div><!-- oncecomment -->
                {% else %}
                <div class="onecomment">
                    <h6>Nobody has said anything about this.</h6>
                    <a href="{{ post.get_absolute_url }}" title="Comment" />comment</a>
                </div>
                {% endif %}
                {% endwith %}
        {% endif %}
        {% endfor %}
        <div id="pagination">
            {% if posts.has_previous %}
                <a href="?page={{ posts.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ posts.number }} of {{ posts.paginator.num_pages }}
            </span>

            {% if posts.has_next %}
                <a href="?page={{ posts.next_page_number }}">next</a>
            {% endif %}
        </div>
    {% else %}
        <p>There is either no news or doc is fixing something. "Fixing".</p>
    {% endif %}
</div>
{% endblock content %}

templates/cafe/user_comment_listing.html
{% extends "layout.html" %}

{% load comments %}

{% block content %}
<div id="news">
    {% if posts %}
        {% for comment in posts %}
        <a href="{{ comment.content_object.get_absolute_url }}" title="{{ comment.content_object.title }}">{{ comment.content_object.title }}</h1></a>
            <div class="onecomment">
                <a href="/user/{{ comment.user.id }}" title="{{ comment.user.get_profile.handle }}'s User Page"><img src="{{ comment.user.get_profile.avatar }}" alt="{{ comment.user.get_profile.handle }}" /></a> {{ comment.user.get_profile.handle }}<br>
                <p>{{ comment.comment|safe }}</p>
            </div><!-- oncecomment -->
            <br>
            <br>
        {% endfor %}
    <div id="pagination">
        {% if posts.has_previous %}
            <a href="?page={{ posts.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ posts.number }} of {{ posts.paginator.num_pages }}
        </span>

        {% if posts.has_next %}
            <a href="?page={{ posts.next_page_number }}">next</a>
        {% endif %}
    </div>
    {% else %}
        <p>There is either no news or doc is fixing something. "Fixing".</p>
    {% endif %}
</div>
{% endblock content %}

templates/cafe/user_post_listing.html
{% extends "layout.html" %}

{% load comments %}

{% block content %}
<div id="news">
    {% if posts %}
        {% for post in posts %}
            {% include "news/single_post.html" %}

            {% with post.get_latest_comment as comment %}
                {% if comment %}
                    <div class="onecomment">
                        <a href="/user/{{ comment.user.id }}" title="{{ comment.user.get_profile.handle }}'s User Page"><img src="{{ comment.user.get_profile.avatar }}" alt="{{ comment.user.get_profile.handle }}" /></a> {{ comment.user.get_profile.handle }}<br>
                        <p>{{ comment.comment|safe|truncatechars:140 }}</p>
                    </div><!-- oncecomment -->
                    {% get_comment_count for post as cnt %}
                    {{ cnt }} post{{ cnt|pluralize }} 
                {% endif %}
                <a href="/post/{{ post.id }}" title="Comment" />comment</a>
            {% endwith %}
        {% endfor %}
        <div id="pagination">
            {% if posts.has_previous %}
                <a href="?page={{ posts.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ posts.number }} of {{ posts.paginator.num_pages }}
            </span>

            {% if posts.has_next %}
                <a href="?page={{ posts.next_page_number }}">next</a>
            {% endif %}
        </div>
    {% else %}
        <p>There is either no news or doc is fixing something. "Fixing".</p>
    {% endif %}
</div>
{% endblock content %}